### ISSUE TITLE
Search Button doesn't work

### ISSUE THREAD

**Issue by ColinFay** [hadley/ggplot2-book#186]
Seems to be GitHub Actions related, we also have the same in https://github.com/Robinlovelace/geocompr/issues/500 and https://github.com/ThinkR-open/engineering-shiny-book/issues/151

**Comment by djnavarro** [comment]
Thanks @ColinFay! 

I've managed to fix this, though not in a very satisfying way. I'm documenting this for the sake of my own sanity because I have a horrible feeling I'm going to encounter this one again...

- The underlying problem is the same as #185: crayon introduces ANSI characters that cause tibbles to display incorrectly in the HTML. This problem propagates to the search button because those same characters are passed into the `search_index.json` file, causing a parsing error. It's a two part fix.

- First, crayon needs to be disabled. As far as I can tell it is sufficient to make changes in the GH actions workflow file (i.e., same fix others have used):

    ```
      - name: Setup R
        uses: r-lib/actions/setup-r@master
        with:
          crayon.enabled: 'FALSE'
    ```

    However, it may be worth noting that I also disabled it within the R markdown (i.e., by setting `options(crayon.enabled = FALSE)` in the `common.R` file). Pretty sure that's redundant but it's working right now and I don't feel inclined to tinker further today :grin: 

- Second, once the crayon issue is fixed, the bookdown site has to be rebuilt from the beginning to make sure every code chunk that prints a tibble is re-rendered. Initially I thought that all I would need to do is disable the cache, push changes, then re-enable it. My recollection is that on Travis CI this trick would flush the cached files and we'd end up with completely refreshed cache. Apparently that doesn't happen on GH actions? Instead, when I re-enabled the bookdown cache it reverted to the old cached files that still contain the offending characters. That seems to be the same problem referred to [here](https://stackoverflow.com/questions/63521430/clear-cache-in-github-actions) and here https://github.com/actions/cache/issues/2?

In any case, this is currently "fixed" in the sense that the search button now works (and this also fixes #185), but if I've understood the discussion over on https://github.com/actions/cache/issues/2 correctly, we'll have to wait for the current bookdown cache on GH actions to expire on its own before re-enabling the relevant lines in `bookdown.yaml`. Sigh. 

(FYI @hadley & @thomasp85)

**Comment by hadley** [comment]
I could've saved you some time if I was awake during your journey of discovery 😄 FWIW GitHub caching is poorly designed because currently there's no way to clear the cache. Presumably this is something that they will fix, but in the meantime we now ensure that every cache key contains a number:

```yaml
      - name: Cache bookdown results
        uses: actions/cache@v1
        with:
          path: _bookdown_files
          key: bookdown-1-${{ hashFiles('**/*Rmd') }}
          restore-keys: bookdown-1-
```

So to "clear" the cache, you just increment that number:

```yaml
      - name: Cache bookdown results
        uses: actions/cache@v1
        with:
          path: _bookdown_files
          key: bookdown-2-${{ hashFiles('**/*Rmd') }}
          restore-keys: bookdown-2-
```
